### ISSUE TITLE
Can't resolve @babel/runtime

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father-next#19]
```bash
Module not found: Error: Can't resolve '@babel/runtime/helpers/defineProperty' in '/Users/congxiaochen/Documents/alita/packages/request/dist'
```

```json
"father": "^4.0.0-alpha.0",
```

```ts
import { defineConfig } from 'father';

export default defineConfig({
    platform:'browser',
    cjs:{
        output:'dist'
    }
});
```

**Comment by PeachScript** [comment]
看来得加一下 father 2 一样的 `@babel/runtime` 安装提示；另外 `platform` 默认值是 `browser` 可以不用配

**Comment by xiaohuoni** [comment]
需要自己安装 @babel/runtime ，就很怪。
pnpm i father@next ---- 这操作不会安装 @babel/runtime 吗？

另外  father 2 也没提示安装 @babel/runtime 啊？？？我一次也没见过！

**Comment by PeachScript** [comment]
father 2 是默认不启用 `runtimeHelpers` 的，你只要开了就会提示要安装了 👀 
之所要项目里显式安装，是因为启用 babel runtime 后产物里会依赖 `@babel/runtime`

**Comment by xiaohuoni** [comment]
father2 默认不启用，father4 默认启用是吧？
runtimeHelpers 能关吗？

**Comment by PeachScript** [comment]
计划是 platform 为 browser 时默认启用，暂不支持关闭

**Comment by PeachScript** [comment]
v4.0.0-alpha.1 改成不强制安装了，安装提示后面做进 doctor 模块里
