### ISSUE TITLE
一些使用问题

### ISSUE THREAD

**Issue by txp1035** [umijs/father-next#40]
时间超过1000ms应该把单位换成s， 
![image](https://user-images.githubusercontent.com/9554297/177875335-494fc8ee-5fbf-44ff-ae6b-07715d67f101.png)

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/177875980-1d70515c-c03d-4b29-b559-88d79b37bace.png)
both 模式无产物

**Comment by txp1035** [comment]
模板还在^4.0.0-alpha.3，白测了

**Comment by PeachScript** [comment]
> build:deps 这个运行无产物是没有列子的原因吗

预打包产物默认路径是 `compiled`

**Comment by PeachScript** [comment]
> 模板还在^4.0.0-alpha.3，白测了,项目例子正常

👍 已更新 tag

**Comment by txp1035** [comment]
混合模式有问题 #42
