### ISSUE TITLE
father 4.0.0-rc.2 打包报错

### ISSUE THREAD

**Issue by twinkle77** [umijs/father-next#43]
1. `npx create-father test`
2. 选择 nodejs、pnpm
3. 新建 aaa 目录，随意 export 一个变量
<img width="774" alt="image" src="https://user-images.githubusercontent.com/17792166/177960859-9731c7f1-16ee-4c53-b68f-585772eadce8.png">
4. 执行 pnpm dev
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/17792166/177960825-665873d2-79b1-4c33-bbc4-e67cc84fbe61.png">
5. command + s 保存一下就能复现

**Comment by PeachScript** [comment]
v4.0.0-rc.3 已修复
