### ISSUE TITLE
安装失败error fsevents@2.3.2: The platform "win32" is incompatible with this module.

### ISSUE THREAD

**Issue by qc-z** [umijs/father-next#44]
yarn add father-next -D
yarn add v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
error fsevents@2.3.2: The platform "win32" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by PeachScript** [comment]
先搜索再提问，ref: https://stackoverflow.com/a/65382529
