### ISSUE TITLE
支持根据 react 版本选择不同的 jsx-runtime

### ISSUE THREAD

**Issue by hasnum-stack** [umijs/father-next#45]
![image](https://user-images.githubusercontent.com/49703360/178392451-2150fb31-239e-42b7-9a6f-901b073e2241.png)
如题,我打印出opts,请问presetReact可以从.fatherrc.ts配置吗
{
  presetEnv: {},
  presetReact: {},
  presetTypeScript: {},      
  pluginTransformRuntime: {},
  pluginLockCoreJS: {},      
  pluginDynamicImportNode: false,
  pluginAutoCSSModules: undefined
}

**Comment by PeachScript** [comment]
目前不支持，修改的具体场景是什么

**Comment by hasnum-stack** [comment]
> 目前不支持，修改的具体场景是什么

比如不想使用presetReact中的jsx_runtime, 需要把runtime改成classic
由于迁移成本问题还需要支持16.13.1版本的react

**Comment by PeachScript** [comment]
没有特殊需要配置还是不打算开放的，你这个场景可以加个根据 React 自动判断的功能，甚至没有 react 的时候也不需要挂载 `presetReact`

有兴趣可以参考 Umi 4 来个 PR：https://github.com/umijs/umi/blob/85a319594ccee8e0ae21b97e09e12d6942da7c48/packages/preset-umi/src/commands/dev/getBabelOpts.ts#L11-L12

**Comment by 18518300669** [comment]
我裂开了，react/jsx-runtime。我排查了几个小时，才找到这个原因。我16.13.1的项目

**Comment by PeachScript** [comment]
[v4.0.0-rc.7](https://github.com/umijs/father-next/releases/tag/v4.0.0-rc.7) 已支持
