### ISSUE TITLE
No loader is configured for ".png" files

### ISSUE THREAD

**Issue by yaodong5063** [umijs/father-next#49]
组件里面有png图片，为什么会出现
No loader is configured for ".png" files，
是loder没解析png类型图片吗，感觉好奇怪也分析不出来
4.0.0-rc.3

export default {
  esm: {
    transformer: "babel",
    output: "./es",
  },
  platform: "node",
  alias: {
    "@/*": "./src/*",
  },
};

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/179455245-7499988c-6533-443b-b968-fa477cf8ff6b.png)

**Comment by yaodong5063** [comment]
@PeachScript  @sorrycc

**Comment by wangxingkang** [comment]
没法复现你的问题 提供下最小可复现包吧
