### ISSUE TITLE
请问下esm或者cjs模式下可以把less转换成css吗

### ISSUE THREAD

**Issue by yaodong5063** [umijs/father-next#50]
同上，less放在组件下面会导致识别不了

**Comment by yaodong5063** [comment]
@PeachScript

**Comment by yaodong5063** [comment]
@wangxingkang

**Comment by yaodong5063** [comment]
extractCSS这个上一版本支持的，这一版本不支持了吗

**Comment by yaodong5063** [comment]
或者这两个模式支持下chainWebpack也行

**Comment by yaodong5063** [comment]
或者这两个模式支持下chainWebpack也行

**Comment by PeachScript** [comment]
目前不考虑支持，新版本的 esm/cjs 不会打包、非 js 只做平行拷贝输出，样式文件建议交给实际项目做编译；如果要产出打包的文件，可以用 umd

**Comment by yaodong5063** [comment]
> 目前不考虑支持，新版本的 esm/cjs 不会打包、非 js 只做平行拷贝输出，样式文件建议交给实际项目做编译；如果要产出打包的文件，可以用 umd

我看了下实际项目也是支持less的，但是打包后下载到node_modules里的包所谓的less并不被支持
https://github.com/yaodong5063/umi4_error.git
这个是我做的例子，
安装好后把DemoModules这个包放到node_modules这个文件夹里，但是并不生效

**Comment by wangxingkang** [comment]
这个我明天看下，我这边使用是不存在这个问题的

**Comment by wangxingkang** [comment]
暂时关闭了，有问题再打开
