### ISSUE TITLE
father build 类型错误输出信息不完整

### ISSUE THREAD

**Issue by fhchina** [umijs/father-next#52]
只生成第一个d.ts文件之后就没有了。tsconfig.json配置都有declararation: true等配置。直接运行tsc命令会报其它错误，但也能正确将其它主要的.d.ts文件都生成出来，除了typings.d.ts没有正确处理。

event - Generate declaration file... 也是输出了的。因此有理由怀疑father build在执行过程中遇到了错误，但吞噬了错误，后续就没有进行了。

father有--verbose这一类的开关没有？找了一遍没发现，建议加上

**Comment by PeachScript** [comment]
提供下最小复现仓库

**Comment by fhchina** [comment]
https://github.com/fhchina/demodumilib.git @PeachScript 就是一个刚用Dumi脚手架生成的项目，然后把Ant Design Pro V4的components/, services/目录拷贝进去，基本上还啥都没开始干

**Comment by fhchina** [comment]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/5356726/180683918-df82f864-e320-4f9e-a372-1b56afad1136.png">
yarn build的结果在我本机是这样的

**Comment by fhchina** [comment]
换成"father": "^2.0.0",之后，father build报错
Build esm with undefined
✖  error     Error: /Users/fanghao/Documents/Development/TypeScript/Project/ant-design-pro-shell/src/components/RightContent/index.tsx(13,11): semantic error TS2339: Property 'initialState' does not exist on type '{ loading: boolean; refresh: () => void; }'. 
但4.0.0-rc不报错

**Comment by PeachScript** [comment]
> https://github.com/fhchina/demodumilib.git @PeachScript 就是一个刚用Dumi脚手架生成的项目，然后把Ant Design Pro V4的components/, services/目录拷贝进去，基本上还啥都没开始干

我试了下有错误信息输出：
![图片](https://user-images.githubusercontent.com/5035925/180699382-444e1ce3-bd01-4fd7-be8c-7bac2f6e9bf3.png)

不过缺少错误位置，需要优化下

**Comment by fhchina** [comment]
这个错误，我现在也碰到了，但是是在加入app.tsx之后，把async getInitialState()加上才会在4.0.0.-rc版本里边出现。不加入的话，4.0.0.-rc不报错。而且用2.x版本报的错完全不同

**Comment by fhchina** [comment]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/5356726/180712172-5f98b759-4d23-4a8b-9723-cde5a710edcc.png">
这个确实应该把整个result.diagnostics数组print出来，而不是第一个。可能后面的信息还更有用一些，这里边这个API，其实是/src/services/ant-design-pro/typings.d.ts里边的declare namespace API， 不知道为啥报这个错

**Comment by fhchina** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/5356726/180714370-bdb55643-9567-4688-ba22-54c907dadba7.png">
换回2.0.0后又报这个错，查看了一下https://github.com/ant-design/ant-design/issues/33853， yarn.lock里边已经是@umijs/plugin-layout@0.18.3这个版本了，不知道为啥还有这个错

**Comment by PeachScript** [comment]
dts 的 error 输出下个版本会优化；father 是组件/库的构建工具，但 ant-design-pro 的代码是依赖 umi 框架的业务代码，不能拷过来直接用 father 构建

**Comment by fhchina** [comment]
确实我也没想清楚，.umi生成的代码在组件库打包下的行为是啥。静态链接？实在不行就只能移除所有umi相关代码，只留纯React组件了。

**Comment by PeachScript** [comment]
[v4.0.0-rc.6](https://github.com/umijs/father-next/releases/tag/v4.0.0-rc.6) 已优化错误输出，closed
