### ISSUE TITLE
请问father4支持lerna仓库吗

### ISSUE THREAD

**Issue by giligiliduang** [umijs/father-next#55]

**Comment by fz6m** [comment]
你说的是 monorepo ？monorepo 和 father 的关系是？

**Comment by wangxingkang** [comment]
father4  去除了 father3 自动处理 monorepo 的逻辑 ， lerna 项目需要单独处理配置和编译，配置可使用extends 继承属性简化配置

**Comment by wangxingkang** [comment]
暂时关闭了，有问题再反馈
