### ISSUE TITLE
缓存导致先跑father dev之后再跑father build 产物还是dev的产物

### ISSUE THREAD

**Issue by cl1107** [umijs/father-next#58]
运行 father dev的产物
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/21985353/183598297-96b33a55-c855-4f86-a255-58089f20bb00.png">
然后再运行father build 产物还是上图所示

删掉缓存重新运行 father build 产物如下图所示
<img width="778" alt="image" src="https://user-images.githubusercontent.com/21985353/183598402-c893793f-f87d-4da6-9067-6a0cea3614e5.png">

**Comment by PeachScript** [comment]
看来 jsx/tsx 文件得把 `NODE_ENV` 纳入 `cacheKey`，欢迎 PR
