### ISSUE TITLE
father 打包时会使用 tsconfig 里的 path，更改源码里的内容

### ISSUE THREAD

**Issue by sevencai** [umijs/father-next#60]
版本号：   "father": "^4.0.0-rc.8",

问题描述：
```
"compilerOptions": {
    "paths": {
      "@test/a": ["../a/src/index.ts"],
     }
  }
```
使用后，使用 `father` 打包，会发现编译后的文件，会将源码中的`import a from @test/a`变成 `import a from '../a/src/index.ts'`。

这个实在是有些不合理，为什么`father `会去读取` tsconfig.json` 里的内容，而不是读取father.rc里的配置做这个事情呢？

**Comment by PeachScript** [comment]
这是个 feature，tsconfig.json 的 `paths` 会被自动转换为 `alias` 配置，减少用户的配置成本（例如 `@` 对应 `src`），但超出 `cwd` 的不会被转换，比如 monorepo 的场景

如果你的项目出现预期外的转换，可以给个最小复现仓库看下

**Comment by sevencai** [comment]
嗯嗯，现在是使用`monorepo`的场景，在`root`下的`tsconfig`里写了`path`, 结果发现被转换了。

我们现在的解决办法是把`path`放到`monorepo`子包内，可以解决问题哈，但是排查了比较久问题。

不知道是否可以把这个`feature`放到你们`fatherrc`里，或者支持一个开关屏蔽掉，不然的话这样直接依据`tsconfig`里的配置做转换用户可能是完全无预期的~
