### ISSUE TITLE
build 没有错误提示

### ISSUE THREAD

**Issue by txp1035** [umijs/father-next#63]
![image](https://user-images.githubusercontent.com/9554297/184556372-896dbba2-bdcc-4f2a-ba78-06befd935cf1.png)
build没有错误提示，执行tsc有提示

**Comment by PeachScript** [comment]
提供下复现仓库

**Comment by txp1035** [comment]
我先记录下，尝试自己解决

**Comment by txp1035** [comment]
我尝试解决，发现那个打包不报错的原因是bundleless构建的问题，我看源码是遍历单文件然后用翻译器转换的，所以依赖出错也不会报出来（不存在依赖检测概念），这里校验应该去doctor校验好还是在转换前校验好呢

**Comment by PeachScript** [comment]
听上去交给 lint 比较合理

**Comment by txp1035** [comment]
> 听上去交给 lint 比较合理

在doctor加一层lint检测？还是用户自己lint啊？

**Comment by PeachScript** [comment]
自己 lint，需要实现 father g lint 命令帮用户生成配置
