### ISSUE TITLE
esm/cjs 打包的时候不支持添加 webpack plugin 吗？

### ISSUE THREAD

**Issue by dongliang1993** [umijs/father-next#71]
使用 dumi 打包组件库的时候，想要对 @ant-design/icons  进行按需加载，所以需要配置  webpack plugin，但是文档没有暴露出配置出来

**Comment by PeachScript** [comment]
cjs/esm 不是走 webpack 的，另外按需加载是 babel-plugin 而不是 webpack plugin，配 extraBabelPlugins 即可

另外该仓库不作为正式仓库，后续交流可到 father 主仓库，issue 关闭

**Comment by fz6m** [comment]
把这个仓库 archive 吧， @PeachScript
